#---------------------
#     ConfigMap
#---------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: node-tekton-config
  labels:
    app: node-tekton-config
  namespace: mytest

data:
  NODETEKTON_PORT: "3010"
  TEKTON_VERSION : "1.0"

---
#---------------------
#     Deployment
#---------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-tekton
  namespace: mytest
spec:
  selector:
    matchLabels:
      app: node-tekton
  template:
    metadata:
      labels:
        app: node-tekton
    spec:
      containers:
      - name: app
        image: vincentparisi/nodetekton:2.0.0
#        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: node-tekton-config

---
#---------------------
# NodePort 
#---------------------
apiVersion: v1
kind: Service
metadata:
  name: node-tekton-np
  namespace: mytest
  labels:
    app: node-tekton
spec:
  type: NodePort
  ports:
   - port: 3010
     nodePort: 30019
  selector:
   app: node-tekton

---
#---------------------
# ClusterIP
#---------------------

apiVersion: v1
kind: Service
metadata:
  namespace: mytest
  name: node-tekton-clu
  labels:
    app: node-tekton-clu
spec:
  type: ClusterIP
  ports:
   - port: 3010
     protocol: TCP
     targetPort: 3010
  selector:
   app: node-tekton
